package ar.edu.unnoba;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;

import ar.edu.unnoba.ast.*;
import ar.edu.unnoba.ast.expresiones.*;
import ar.edu.unnoba.ast.expresiones.logicas.*;
import ar.edu.unnoba.ast.expresiones.matematicas.*;
import ar.edu.unnoba.ast.sentencias.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

// ---------------------------------------------------------
//  Código Java incrustado para el Parser
// ---------------------------------------------------------
parser code {:
    public TablaSimbolos tablaSimbolos = new TablaSimbolos();
    
    public int cantidadCiclosActivos = 0;

    // Método para manejar errores sintácticos recuperables
    public void syntax_error(Symbol symbol) {
        ComplexSymbol complexSymbol = (ComplexSymbol) symbol;
        int linea = complexSymbol.getLeft().getLine();
        int columna = complexSymbol.getLeft().getColumn();
        String nombreToken = complexSymbol.getName();
        System.err.println("\nError Sintáctico: Línea " + linea +  ", columna " + columna + ". No se esperaba el componente: " + nombreToken + ".");
    }

    // Método para manejar errores sintácticos fatales
    public void unrecovered_syntax_error(Symbol symbol) throws java.lang.Exception {
        ComplexSymbol complexSymbol = (ComplexSymbol) symbol;
        int linea = complexSymbol.getLeft().getLine();
        int columna = complexSymbol.getLeft().getColumn();
        System.err.println("Error Fatal: No se pudo recuperar del error en la línea " + linea + ", columna " + columna + ".");
        throw new Exception("Error Sintáctico Fatal.");
    }

    public Expresion[] castearOperandos(Expresion e1, Expresion e2) {
        if (e1.getTipoDato() == TipoDato.INT && e2.getTipoDato() == TipoDato.FLOAT) {
            return new Expresion[]{ new Conversion(e1, TipoDato.FLOAT), e2 };
        } else if (e1.getTipoDato() == TipoDato.FLOAT && e2.getTipoDato() == TipoDato.INT) {
            return new Expresion[]{ e1, new Conversion(e2, TipoDato.FLOAT) };
        }

        return new Expresion[]{ e1, e2 };
    }

    // Estilo de moda generada. Los elementos van desde lo más interno a lo más externo.

    /*
        public double encontrarModa(double[] arreglo) {
            if (arreglo.length == 0) return -1.0;
            double moda = arreglo[0];
            int frecuenciaMaxima = 0;
            for (int i = 0; i < arreglo.length; i++) {
                int frecuenciaActual = 0;
                for (int j = 0; j < arreglo.length; j++) {
                    if (arreglo[i] == arreglo[j]) frecuenciaActual++;
                }
                if (frecuenciaActual > frecuenciaMaxima) {
                    frecuenciaMaxima = frecuenciaActual;
                    moda = arreglo[i];
                }
            }
            return moda;
        }
    */

    // Identificadores para el algoritmo (Coinciden con la clase empaquetadora final Moda.java)
    private Identificador idArray(int n) { return new Identificador("moda_array", TipoDato.ARRAY, n); }
    private Identificador idIndiceExterno() { return new Identificador("moda_indice_externo", TipoDato.INT, 0); }
    private Identificador idIndiceInterno() { return new Identificador("moda_indice_interno", TipoDato.INT, 0); }
    private Identificador idFrecuenciaActual() { return new Identificador("moda_frecuencia_actual", TipoDato.INT, 0); }
    private Identificador idFrecuenciaMaxima() { return new Identificador("moda_frecuencia_maxima", TipoDato.INT, 0); }
    private Identificador idValorModa() { return new Identificador("moda_valor_resultado", TipoDato.FLOAT, 0); }
    
    private Constante constanteCero() { return new Constante("0", TipoDato.INT, 0); }
    private Constante constanteUno() { return new Constante("1", TipoDato.INT, 0); }
    private Constante constanteN(int n) { return new Constante(String.valueOf(n), TipoDato.INT, 0); }

    public Expresion construirModa(Expresion arregloEntrada) {
        int n = arregloEntrada.getDimensionArreglo();
        List<Sentencia> algoritmo = new ArrayList<>();
        
        // Inicialización de las variables
        algoritmo.add(new Asignacion(idArray(n), arregloEntrada));

        List<Sentencia> cuerpoVacio = new ArrayList<>();
        tablaSimbolos.agregarString("La lista esta vacia.\\n");
        cuerpoVacio.add(new Print(new Constante("La lista esta vacia.\\n", TipoDato.STRING, 0)));
        cuerpoVacio.add(new Asignacion(idValorModa(), new Constante("-1.0", TipoDato.FLOAT, 0)));

        List<Sentencia> cuerpoNormal = new ArrayList<>();
        cuerpoNormal.add(new Asignacion(idFrecuenciaMaxima(), constanteCero()));
        cuerpoNormal.add(new Asignacion(idIndiceExterno(), constanteCero()));
        cuerpoNormal.add(new Asignacion(idValorModa(), new AccesoArreglo(idArray(n), constanteCero())));
        
        // --- BUCLE INTERNO ---
        AccesoArreglo elementoExterno = new AccesoArreglo(idArray(n), idIndiceExterno());
        AccesoArreglo elementoInterno = new AccesoArreglo(idArray(n), idIndiceInterno());
        
        List<Sentencia> cuerpoIfIguales = new ArrayList<>();
        Suma incrementoFrecuencia = new Suma(TipoDato.INT, idFrecuenciaActual(), constanteUno());
        incrementoFrecuencia.setDimensionArreglo(0);
        cuerpoIfIguales.add(new Asignacion(idFrecuenciaActual(), incrementoFrecuencia));
        If ifElementosIguales = new If(new Igual(elementoExterno, elementoInterno), cuerpoIfIguales, new ArrayList<Sentencia>());
        
        List<Sentencia> cuerpoBucleInterno = new ArrayList<>();
        cuerpoBucleInterno.add(ifElementosIguales);
        Suma incrementoIndiceInterno = new Suma(TipoDato.INT, idIndiceInterno(), constanteUno());
        incrementoIndiceInterno.setDimensionArreglo(0);
        cuerpoBucleInterno.add(new Asignacion(idIndiceInterno(), incrementoIndiceInterno));
        While bucleInterno = new While(new Clausula("BLOQUE_BUCLE_INTERNO", new Menor(idIndiceInterno(), constanteN(n)), cuerpoBucleInterno), new ArrayList<Clausula>());
        
        // --- BUCLE EXTERNO ---
        List<Sentencia> cuerpoIfNuevaModa = new ArrayList<>();
        cuerpoIfNuevaModa.add(new Asignacion(idFrecuenciaMaxima(), idFrecuenciaActual()));
        cuerpoIfNuevaModa.add(new Asignacion(idValorModa(), new AccesoArreglo(idArray(n), idIndiceExterno())));
        If ifNuevaModa = new If(new Mayor(idFrecuenciaActual(), idFrecuenciaMaxima()), cuerpoIfNuevaModa, new ArrayList<Sentencia>());
        
        List<Sentencia> cuerpoBucleExterno = new ArrayList<>();
        cuerpoBucleExterno.add(new Asignacion(idIndiceInterno(), constanteCero()));
        cuerpoBucleExterno.add(new Asignacion(idFrecuenciaActual(), constanteCero()));
        cuerpoBucleExterno.add(bucleInterno);
        cuerpoBucleExterno.add(ifNuevaModa);
        Suma incrementoIndiceExterno = new Suma(TipoDato.INT, idIndiceExterno(), constanteUno());
        incrementoIndiceExterno.setDimensionArreglo(0);
        cuerpoBucleExterno.add(new Asignacion(idIndiceExterno(), incrementoIndiceExterno));
        While bucleExterno = new While(new Clausula("BLOQUE_BUCLE_EXTERNO", new Menor(idIndiceExterno(), constanteN(n)), cuerpoBucleExterno), new ArrayList<Clausula>());
        
        cuerpoNormal.add(bucleExterno);

        If comprobacionArregloVacio = new If(new Igual(constanteN(n), constanteCero()), cuerpoVacio, cuerpoNormal);
        algoritmo.add(comprobacionArregloVacio);
        
        // Retornar paquete final
        return new Moda(algoritmo, idValorModa(), n);
    }
:}

// ---------------------------------------------------------
//  Declaración de Terminales (Tokens del Lexer)
// ---------------------------------------------------------

// Indentación
terminal INDENT, DEDENT;

// Palabras reservadas
terminal PROGRAM, WHILE, ALT_WHILE, BREAK, CONTINUE, IF, ELIF, ELSE;
terminal PRINT, READ_INT, READ_FLOAT, READ_BOOL;
terminal INT, FLOAT, BOOLEAN, ARRAY, MODA;

// Operadores aritméticos
terminal SUMA, RESTA, MULTIPLICACION, DIVISION, MENOS_UNARIO;

// Operadores relacionales y lógicos
terminal ASIGNACION, IGUAL, DESIGUAL, MAYOR_IGUAL, MENOR_IGUAL, MAYOR, MENOR;
terminal CONJUNCION, DISYUNCION, NEGACION;

// Puntuación
terminal PARENTESIS_IZQ, PARENTESIS_DER, CORCHETE_IZQ, CORCHETE_DER;
terminal COMA, DOS_PUNTOS;

// Literales (Contienen valores)
terminal String IDENTIFICADOR, ENTERO, FLOTANTE, BOOLEANO, CADENA, ARREGLO;

// ---------------------------------------------------------
//  Declaración de No Terminales
// ---------------------------------------------------------
non terminal Programa inicio, programa;
non terminal List<Declaracion> zona_declaraciones, lista_declaraciones;
non terminal Declaracion declaracion;
non terminal Simbolo tipo;
non terminal List<Identificador> lista_variables;

non terminal List<Sentencia> bloque_programa, sentencias, bloque_else;
non terminal Sentencia sentencia, sentencia_asignacion, sentencia_print, sentencia_control, sentencia_if, sentencia_while;
non terminal List<Clausula> lista_elif, lista_alt_while;

non terminal Expresion expr, expr_and, expr_not, expr_rel, expr_arit, term, factor, expr_moda;

// ---------------------------------------------------------
//  Precedencia y Asociatividad
// ---------------------------------------------------------

// ---------------------------------------------------------
//  Punto de partida
// ---------------------------------------------------------
start with inicio;

// ---------------------------------------------------------
//  Reglas Gramaticales
// ---------------------------------------------------------
inicio ::= programa:p {:
            System.out.println("[PARSER] Símbolo distinguido reconocido\n");
            tablaSimbolos.generarArchivo("tablaSimbolos.txt");
            RESULT = p;
        :} ;

programa ::= zona_declaraciones:zd bloque_programa:bp {:
            System.out.println("[PARSER] REGLA: programa -> zona_declaraciones bloque_programa");
            RESULT = new Programa(zd, bp);
        :} ;

//
// --- ZONA DE DECLARACIONES ---
//

zona_declaraciones ::= lista_declaraciones:lista {:
            System.out.println("[PARSER] REGLA: zona_declaraciones -> lista_declaraciones");
            RESULT = lista;
        :} | /* Vacío */ {:
            RESULT = new ArrayList<Declaracion>();
        :} ;

lista_declaraciones ::= lista_declaraciones:lista declaracion:d {:
            lista.add(d);
            RESULT = lista;
        :} | declaracion:d {:
            List<Declaracion> lista = new ArrayList<>();
            lista.add(d);
            RESULT = lista;
        :} ;

declaracion ::= tipo:t DOS_PUNTOS lista_variables:l {:
            System.out.println("[PARSER] REGLA: declaracion -> tipo DOS_PUNTOS lista_variables");
            
            for (Identificador id : l) {
                parser.tablaSimbolos.agregarVariable(id.getNombre(), t);
            }

            RESULT = new Declaracion(t, l);
        :} ;

tipo ::= INT {: RESULT = new Simbolo(TipoDato.INT, 0); :}
        | FLOAT {: RESULT = new Simbolo(TipoDato.FLOAT, 0); :}
        | BOOLEAN {: RESULT = new Simbolo(TipoDato.BOOLEAN, 0); :}
        | ARRAY CORCHETE_IZQ ENTERO:e CORCHETE_DER {: RESULT = new Simbolo(TipoDato.ARRAY, Integer.parseInt(e)); :} ;

lista_variables ::= lista_variables:lista COMA IDENTIFICADOR:id {:
            lista.add(new Identificador(id));
            RESULT = lista;
        :} | IDENTIFICADOR:id {:
            List<Identificador> lista = new ArrayList<>();
            lista.add(new Identificador(id));
            RESULT = lista;
        :} ;

//
// --- BLOQUE PRINCIPAL (PROGRAM) ---
//

bloque_programa ::= PROGRAM INDENT sentencias:s DEDENT {:
            System.out.println("[PARSER] REGLA: bloque_programa -> PROGRAM INDENT sentencias DEDENT");
            RESULT = s;
        :} | PROGRAM {:
            RESULT = new ArrayList<Sentencia>();
        :} ;

sentencias ::= sentencias:lista sentencia:s {:
            lista.add(s);
            RESULT = lista;
        :} | sentencia:s {:
            List<Sentencia> lista = new ArrayList<>();
            lista.add(s);
            RESULT = lista;
        :} ;

sentencia ::= sentencia_asignacion:s {: RESULT = s; :}
        | sentencia_print:s {: RESULT = s; :}
        | sentencia_control:s {: RESULT = s; :}
        | sentencia_if:s {: RESULT = s; :}
        | sentencia_while:s {: RESULT = s; :} ;

sentencia_asignacion ::= IDENTIFICADOR:id ASIGNACION expr:e {:
            TipoDato tipoVariable = ValidadorSemantico.verificarExistenciaVariable(id, parser.tablaSimbolos);
            Simbolo simboloVariable = parser.tablaSimbolos.obtenerSimbolo(id);
            ValidadorSemantico.verificarAsignacion(tipoVariable, e.getTipoDato(), simboloVariable.getDimensionArreglo(), e.getDimensionArreglo());
            
            if ((tipoVariable == TipoDato.FLOAT || tipoVariable == TipoDato.ARRAY) && e.getTipoDato() == TipoDato.INT) {
                e = new Conversion(e, TipoDato.FLOAT);
            }
            
            System.out.println("[PARSER] REGLA: sentencia_asignacion -> IDENTIFICADOR ASIGNACION expr");
            RESULT = new Asignacion(new Identificador(id, tipoVariable, simboloVariable.getDimensionArreglo()), e);
        :} | IDENTIFICADOR:id CORCHETE_IZQ expr:idx CORCHETE_DER ASIGNACION expr:e {:
            TipoDato tipoVariable = ValidadorSemantico.verificarExistenciaVariable(id, parser.tablaSimbolos);
            Simbolo simboloVariable = parser.tablaSimbolos.obtenerSimbolo(id);
            ValidadorSemantico.verificarAsignacionArreglo(id, tipoVariable, idx.getTipoDato(), e.getTipoDato());

            if (tipoVariable == TipoDato.ARRAY && e.getTipoDato() == TipoDato.INT) {
                e = new Conversion(e, TipoDato.FLOAT);
            }

            System.out.println("[PARSER] REGLA: sentencia_asignacion -> IDENTIFICADOR [ expr ] ASIGNACION expr");
            RESULT = new AsignacionArreglo(new Identificador(id, tipoVariable, simboloVariable.getDimensionArreglo()), idx, e);
        :} ;

sentencia_print ::= PRINT PARENTESIS_IZQ expr:e PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: sentencia_print -> PRINT ( expr )");
            RESULT = new Print(e);
        :} | PRINT PARENTESIS_IZQ CADENA:c PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: sentencia_print -> PRINT ( CADENA )");
            parser.tablaSimbolos.agregarString(c);
            RESULT = new Print(new Constante(c, TipoDato.STRING, 0));
        :} ;

sentencia_control ::= BREAK {:
            ValidadorSemantico.verificarBreakContinue(parser.cantidadCiclosActivos, "BREAK");
            System.out.println("[PARSER] REGLA: sentencia_control -> BREAK");
            RESULT = new Break();
        :} | CONTINUE {:
            ValidadorSemantico.verificarBreakContinue(parser.cantidadCiclosActivos, "CONTINUE");
            System.out.println("[PARSER] REGLA: sentencia_control -> CONTINUE");
            RESULT = new Continue();
        :} ;

sentencia_if ::= IF expr:cond INDENT sentencias:cuerpo DEDENT lista_elif:elifs bloque_else:belse {:
            ValidadorSemantico.verificarCondicionEstructuraControl(cond.getTipoDato(), "IF");
            System.out.println("[PARSER] REGLA: sentencia_if");

            List<Sentencia> elseActual = belse;

            Collections.reverse(elifs);
            for (Clausula clausula : elifs) {
                If ifAnidado = new If(clausula.condicion, clausula.cuerpo, elseActual);
                elseActual = new ArrayList<Sentencia>();
                elseActual.add(ifAnidado);
            }

            RESULT = new If(cond, cuerpo, elseActual);
        :} ;

lista_elif ::= lista_elif:lista ELIF expr:cond INDENT sentencias:cuerpo DEDENT {:
            ValidadorSemantico.verificarCondicionEstructuraControl(cond.getTipoDato(), "ELIF");
            lista.add(new Clausula("BLOQUE_ELIF", cond, cuerpo));
            RESULT = lista;
        :} | /* Vacío */ {:
            RESULT = new ArrayList<Clausula>();
        :} ;

bloque_else ::= ELSE INDENT sentencias:s DEDENT {: RESULT = s; :}
        | /* Vacío */ {: RESULT = null; :} ;

sentencia_while ::= WHILE {: parser.cantidadCiclosActivos++; :} expr:cond INDENT sentencias:cuerpo DEDENT lista_alt_while:alts {:
            parser.cantidadCiclosActivos--;
            ValidadorSemantico.verificarCondicionEstructuraControl(cond.getTipoDato(), "WHILE");
            System.out.println("[PARSER] REGLA: sentencia_while");
            RESULT = new While(new Clausula("BLOQUE_WHILE", cond, cuerpo), alts);
        :} ;

lista_alt_while ::= lista_alt_while:lista ALT_WHILE expr:cond INDENT sentencias:cuerpo DEDENT {:
            ValidadorSemantico.verificarCondicionEstructuraControl(cond.getTipoDato(), "ALT_WHILE");
            lista.add(new Clausula("BLOQUE_ALT_WHILE", cond, cuerpo));
            RESULT = lista;
        :} | /* Vacío */ {:
            RESULT = new ArrayList<Clausula>();
        :} ;

// --- EXPRESIONES LÓGICAS (OR) ---
expr ::= expr_and:e1 DISYUNCION expr:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionLogicaBinaria("||", e1.getTipoDato(), e2.getTipoDato());
            System.out.println("[PARSER] REGLA: expr -> expr_and DISYUNCION expr");
            RESULT = new Disyuncion(e1, e2);
        :} | expr_and:e {: RESULT = e; :} ;

// --- EXPRESIONES LÓGICAS (AND) ---
expr_and ::= expr_not:e1 CONJUNCION expr_and:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionLogicaBinaria("&&", e1.getTipoDato(), e2.getTipoDato());
            System.out.println("[PARSER] REGLA: expr_and -> expr_not CONJUNCION expr_and");
            RESULT = new Conjuncion(e1, e2);
        :} | expr_not:e {: RESULT = e; :} ;

// --- EXPRESIONES LÓGICAS (NOT) ---
expr_not ::= NEGACION expr_not:e {:
            TipoDato resultado = ValidadorSemantico.verificarNegacionLogica(e.getTipoDato());
            System.out.println("[PARSER] REGLA: expr_not -> NEGACION expr_not");
            RESULT = new Negacion(e);
        :} | expr_rel:e {: RESULT = e; :} ;

// --- EXPRESIONES RELACIONALES ---
// (No son asociativas, por lo que fuerzan a que se compare un valor aritmético con otro)
expr_rel ::= expr_arit:e1 IGUAL expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria("==", e1.getTipoDato(), e2.getTipoDato());
            
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit IGUAL expr_arit");
            RESULT = new Igual(e1, e2);
        :} | expr_arit:e1 DESIGUAL expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria("!=", e1.getTipoDato(), e2.getTipoDato());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit DESIGUAL expr_arit");
            RESULT = new Desigual(e1, e2);
        :} | expr_arit:e1 MAYOR_IGUAL expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria(">=", e1.getTipoDato(), e2.getTipoDato());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MAYOR_IGUAL expr_arit");
            RESULT = new MayorIgual(e1, e2);
        :} | expr_arit:e1 MENOR_IGUAL expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria("<=", e1.getTipoDato(), e2.getTipoDato());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MENOR_IGUAL expr_arit");
            RESULT = new MenorIgual(e1, e2);
        :} | expr_arit:e1 MAYOR expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria(">", e1.getTipoDato(), e2.getTipoDato());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MAYOR expr_arit");
            RESULT = new Mayor(e1, e2);
        :} | expr_arit:e1 MENOR expr_arit:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionRelacionalBinaria("<", e1.getTipoDato(), e2.getTipoDato());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MENOR expr_arit");
            RESULT = new Menor(e1, e2);
        :} | expr_arit:e {: RESULT = e; :} ;

// --- EXPRESIONES ARITMÉTICAS (+, -) ---
// (Asociativas por izquierda)
expr_arit ::= expr_arit:e1 SUMA term:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionMatematicaBinaria(e1.getTipoDato(), e2.getTipoDato(), e1.getDimensionArreglo(), e2.getDimensionArreglo());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_arit -> expr_arit SUMA term");
            Suma suma = new Suma(resultado, e1, e2);
            suma.setDimensionArreglo(e1.getTipoDato() == TipoDato.ARRAY ? e1.getDimensionArreglo() : e2.getDimensionArreglo());
            RESULT = suma;
        :} | expr_arit:e1 RESTA term:e2 {:
            TipoDato resultado = ValidadorSemantico.verificarOperacionMatematicaBinaria(e1.getTipoDato(), e2.getTipoDato(), e1.getDimensionArreglo(), e2.getDimensionArreglo());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: expr_arit -> expr_arit RESTA term");
            Resta resta = new Resta(resultado, e1, e2);
            resta.setDimensionArreglo(e1.getTipoDato() == TipoDato.ARRAY ? e1.getDimensionArreglo() : e2.getDimensionArreglo());
            RESULT = resta;
        :} | term:e {: RESULT = e; :} ;

// --- TÉRMINOS (*, /) ---
// (Tienen mayor precedencia que la suma o resta)
term ::= term:e1 MULTIPLICACION factor:e2 {: 
            TipoDato resultado = ValidadorSemantico.verificarOperacionMatematicaBinaria(e1.getTipoDato(), e2.getTipoDato(), e1.getDimensionArreglo(), e2.getDimensionArreglo());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: term -> term MULTIPLICACION factor");
            Multiplicacion multiplicacion = new Multiplicacion(resultado, e1, e2);
            multiplicacion.setDimensionArreglo(e1.getTipoDato() == TipoDato.ARRAY ? e1.getDimensionArreglo() : e2.getDimensionArreglo());
            RESULT = multiplicacion;
        :} | term:e1 DIVISION factor:e2 {: 
            TipoDato resultado = ValidadorSemantico.verificarOperacionMatematicaBinaria(e1.getTipoDato(), e2.getTipoDato(), e1.getDimensionArreglo(), e2.getDimensionArreglo());
                        
            Expresion[] operandos = parser.castearOperandos(e1, e2);
            e1 = operandos[0];
            e2 = operandos[1];
            
            System.out.println("[PARSER] REGLA: term -> term DIVISION factor");
            Division division = new Division(resultado, e1, e2);
            division.setDimensionArreglo(e1.getTipoDato() == TipoDato.ARRAY ? e1.getDimensionArreglo() : e2.getDimensionArreglo());
            RESULT = division;
        :} | factor:e {: RESULT = e; :} ;

// --- FACTORES (Valores atómicos y máxima precedencia) ---
factor ::= RESTA factor:f {:
            TipoDato resultado = ValidadorSemantico.verificarMenosUnario(f.getTipoDato());
            MenosUnario menosUnario = new MenosUnario(resultado, f);
            menosUnario.setDimensionArreglo(f.getDimensionArreglo());
            System.out.println("[PARSER] REGLA: factor -> MENOS_UNARIO factor");
            RESULT = menosUnario;
        :} | PARENTESIS_IZQ expr:e PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: factor -> ( expr )");
            RESULT = e;
        :} | IDENTIFICADOR:id {:
            TipoDato tipo = ValidadorSemantico.verificarExistenciaVariable(id, parser.tablaSimbolos);
            Simbolo simbolo = parser.tablaSimbolos.obtenerSimbolo(id);
            System.out.println("[PARSER] REGLA: factor -> IDENTIFICADOR");
            RESULT = new Identificador(id, tipo, simbolo.getDimensionArreglo());
        :} | IDENTIFICADOR:id CORCHETE_IZQ expr:e CORCHETE_DER {:
            TipoDato tipoVariable = ValidadorSemantico.verificarExistenciaVariable(id, parser.tablaSimbolos);
            TipoDato resultado = ValidadorSemantico.verificarAccesoArreglo(id, tipoVariable, e.getTipoDato());
            Simbolo simbolo = parser.tablaSimbolos.obtenerSimbolo(id);
            System.out.println("[PARSER] REGLA: factor -> IDENTIFICADOR [ expr ]");
            RESULT = new AccesoArreglo(new Identificador(id, tipoVariable, simbolo.getDimensionArreglo()), e);
        :} | ENTERO:e {:
            System.out.println("[PARSER] REGLA: factor -> ENTERO");
            RESULT = new Constante(e, TipoDato.INT, 0);
        :} | FLOTANTE:f {:
            System.out.println("[PARSER] REGLA: factor -> FLOTANTE");
            RESULT = new Constante(f, TipoDato.FLOAT, 0);
        :} | BOOLEANO:b {:
            System.out.println("[PARSER] REGLA: factor -> BOOLEANO");
            RESULT = new Constante(b, TipoDato.BOOLEAN, 0);
        :} | ARREGLO:a {:
            int dimension = ValidadorSemantico.calcularDimensionArregloConstante(a);
            System.out.println("[PARSER] REGLA: factor -> ARREGLO");
            RESULT = new Constante(a, TipoDato.ARRAY, dimension);
        :} | expr_moda:m {:
            RESULT = m;
        :} | READ_INT PARENTESIS_IZQ PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: factor -> READ_INT ()");
            RESULT = new ReadInt();
        :} | READ_FLOAT PARENTESIS_IZQ PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: factor -> READ_FLOAT ()");
            RESULT = new ReadFloat();
        :} | READ_BOOL PARENTESIS_IZQ PARENTESIS_DER {:
            System.out.println("[PARSER] REGLA: factor -> READ_BOOL ()");
            RESULT = new ReadBool();
        :} ;

expr_moda ::= MODA PARENTESIS_IZQ expr:e PARENTESIS_DER {:
            TipoDato resultado = ValidadorSemantico.verificarModa(e.getTipoDato());
            System.out.println("[PARSER] REGLA: expr_moda -> MODA ( expr )");
            RESULT = parser.construirModa(e);
        :} ;
