
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package unnoba;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\106\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\004\003\000\002\004\002\000\002\005\004" +
    "\000\002\005\003\000\002\006\005\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\006\000\002" +
    "\010\005\000\002\010\003\000\002\011\006\000\002\011" +
    "\003\000\002\013\003\000\002\013\002\000\002\012\004" +
    "\000\002\012\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\015\005\000\002\015\010\000\002\016\006\000\002\016" +
    "\006\000\002\024\003\000\002\024\003\000\002\017\011" +
    "\000\002\020\010\000\002\020\002\000\002\021\006\000" +
    "\002\021\002\000\002\022\010\000\002\023\010\000\002" +
    "\023\002\000\002\025\005\000\002\025\003\000\002\026" +
    "\005\000\002\026\003\000\002\027\005\000\002\027\005" +
    "\000\002\027\005\000\002\027\005\000\002\027\005\000" +
    "\002\027\005\000\002\027\003\000\002\030\005\000\002" +
    "\030\005\000\002\030\003\000\002\031\005\000\002\031" +
    "\005\000\002\031\003\000\002\032\004\000\002\032\004" +
    "\000\002\032\005\000\002\032\003\000\002\032\006\000" +
    "\002\032\003\000\002\032\003\000\002\032\003\000\002" +
    "\032\003\000\002\032\003\000\002\032\005\000\002\032" +
    "\005\000\002\032\005\000\002\033\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\014\006\ufffd\022\005\023\015\024\007\025" +
    "\006\001\002\000\004\002\000\001\002\000\004\053\ufff9" +
    "\001\002\000\004\050\207\001\002\000\004\053\ufff7\001" +
    "\002\000\004\002\206\001\002\000\004\006\025\001\002" +
    "\000\014\006\ufffb\022\ufffb\023\ufffb\024\ufffb\025\ufffb\001" +
    "\002\000\014\006\ufffe\022\005\023\015\024\007\025\006" +
    "\001\002\000\004\053\016\001\002\000\004\053\ufff8\001" +
    "\002\000\004\054\020\001\002\000\016\006\ufffa\022\ufffa" +
    "\023\ufffa\024\ufffa\025\ufffa\052\021\001\002\000\016\006" +
    "\ufff4\022\ufff4\023\ufff4\024\ufff4\025\ufff4\052\ufff4\001\002" +
    "\000\004\054\022\001\002\000\016\006\ufff5\022\ufff5\023" +
    "\ufff5\024\ufff5\025\ufff5\052\ufff5\001\002\000\014\006\ufffc" +
    "\022\ufffc\023\ufffc\024\ufffc\025\ufffc\001\002\000\004\002" +
    "\uffff\001\002\000\006\002\ufff2\004\026\001\002\000\020" +
    "\005\ufff0\007\027\011\044\012\040\013\035\016\036\054" +
    "\043\001\002\000\032\017\061\020\057\021\052\026\070" +
    "\030\071\045\051\046\054\054\066\055\067\056\053\057" +
    "\056\061\047\001\002\000\020\005\uffeb\007\uffeb\011\uffeb" +
    "\012\uffeb\013\uffeb\016\uffeb\054\uffeb\001\002\000\004\005" +
    "\173\001\002\000\020\005\uffee\007\uffee\011\uffee\012\uffee" +
    "\013\uffee\016\uffee\054\uffee\001\002\000\020\005\uffe9\007" +
    "\uffe9\011\uffe9\012\uffe9\013\uffe9\016\uffe9\054\uffe9\001\002" +
    "\000\020\005\uffed\007\uffed\011\uffed\012\uffed\013\uffed\016" +
    "\uffed\054\uffed\001\002\000\032\017\061\020\057\021\052" +
    "\026\070\030\071\045\051\046\054\054\066\055\067\056" +
    "\053\057\056\061\047\001\002\000\004\046\147\001\002" +
    "\000\020\005\uffea\007\uffea\011\uffea\012\uffea\013\uffea\016" +
    "\uffea\054\uffea\001\002\000\020\005\uffe3\007\uffe3\011\uffe3" +
    "\012\uffe3\013\uffe3\016\uffe3\054\uffe3\001\002\000\020\005" +
    "\uffec\007\uffec\011\uffec\012\uffec\013\uffec\016\uffec\054\uffec" +
    "\001\002\000\020\005\ufff1\007\027\011\044\012\040\013" +
    "\035\016\036\054\043\001\002\000\006\034\045\050\046" +
    "\001\002\000\020\005\uffe4\007\uffe4\011\uffe4\012\uffe4\013" +
    "\uffe4\016\uffe4\054\uffe4\001\002\000\032\017\061\020\057" +
    "\021\052\026\070\030\071\045\051\046\054\054\066\055" +
    "\067\056\053\057\056\061\047\001\002\000\032\017\061" +
    "\020\057\021\052\026\070\030\071\045\051\046\054\054" +
    "\066\055\067\056\053\057\056\061\047\001\002\000\056" +
    "\004\uffc1\005\uffc1\007\uffc1\011\uffc1\012\uffc1\013\uffc1\016" +
    "\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\035\uffc1\036\uffc1" +
    "\037\uffc1\040\uffc1\041\uffc1\042\uffc1\043\uffc1\044\uffc1\047" +
    "\uffc1\051\uffc1\054\uffc1\001\002\000\004\051\142\001\002" +
    "\000\032\017\061\020\057\021\052\026\070\030\071\045" +
    "\051\046\054\054\066\055\067\056\053\057\056\061\047" +
    "\001\002\000\004\046\137\001\002\000\056\004\uffc3\005" +
    "\uffc3\007\uffc3\011\uffc3\012\uffc3\013\uffc3\016\uffc3\027\uffc3" +
    "\030\uffc3\031\uffc3\032\uffc3\035\uffc3\036\uffc3\037\uffc3\040" +
    "\uffc3\041\uffc3\042\uffc3\043\uffc3\044\uffc3\047\uffc3\051\uffc3" +
    "\054\uffc3\001\002\000\032\017\061\020\057\021\052\026" +
    "\070\030\071\045\051\046\054\054\066\055\067\056\053" +
    "\057\056\061\047\001\002\000\030\004\uffd9\005\uffd9\007" +
    "\uffd9\011\uffd9\012\uffd9\013\uffd9\016\uffd9\044\133\047\uffd9" +
    "\051\uffd9\054\uffd9\001\002\000\056\004\uffc2\005\uffc2\007" +
    "\uffc2\011\uffc2\012\uffc2\013\uffc2\016\uffc2\027\uffc2\030\uffc2" +
    "\031\uffc2\032\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\041" +
    "\uffc2\042\uffc2\043\uffc2\044\uffc2\047\uffc2\051\uffc2\054\uffc2" +
    "\001\002\000\004\046\131\001\002\000\056\004\uffc0\005" +
    "\uffc0\007\uffc0\011\uffc0\012\uffc0\013\uffc0\016\uffc0\027\uffc0" +
    "\030\uffc0\031\uffc0\032\uffc0\035\uffc0\036\uffc0\037\uffc0\040" +
    "\uffc0\041\uffc0\042\uffc0\043\uffc0\044\uffc0\047\uffc0\051\uffc0" +
    "\054\uffc0\001\002\000\004\046\127\001\002\000\032\004" +
    "\uffd7\005\uffd7\007\uffd7\011\uffd7\012\uffd7\013\uffd7\016\uffd7" +
    "\043\125\044\uffd7\047\uffd7\051\uffd7\054\uffd7\001\002\000" +
    "\056\004\uffca\005\uffca\007\uffca\011\uffca\012\uffca\013\uffca" +
    "\016\uffca\027\uffca\030\uffca\031\uffca\032\uffca\035\uffca\036" +
    "\uffca\037\uffca\040\uffca\041\uffca\042\uffca\043\uffca\044\uffca" +
    "\047\uffca\051\uffca\054\uffca\001\002\000\056\004\uffcd\005" +
    "\uffcd\007\uffcd\011\uffcd\012\uffcd\013\uffcd\016\uffcd\027\uffcd" +
    "\030\uffcd\031\116\032\117\035\uffcd\036\uffcd\037\uffcd\040" +
    "\uffcd\041\uffcd\042\uffcd\043\uffcd\044\uffcd\047\uffcd\051\uffcd" +
    "\054\uffcd\001\002\000\052\004\uffd0\005\uffd0\007\uffd0\011" +
    "\uffd0\012\uffd0\013\uffd0\016\uffd0\027\104\030\101\035\103" +
    "\036\102\037\110\040\106\041\107\042\105\043\uffd0\044" +
    "\uffd0\047\uffd0\051\uffd0\054\uffd0\001\002\000\060\004\uffc6" +
    "\005\uffc6\007\uffc6\011\uffc6\012\uffc6\013\uffc6\016\uffc6\027" +
    "\uffc6\030\uffc6\031\uffc6\032\uffc6\035\uffc6\036\uffc6\037\uffc6" +
    "\040\uffc6\041\uffc6\042\uffc6\043\uffc6\044\uffc6\047\uffc6\050" +
    "\076\051\uffc6\054\uffc6\001\002\000\056\004\uffc4\005\uffc4" +
    "\007\uffc4\011\uffc4\012\uffc4\013\uffc4\016\uffc4\027\uffc4\030" +
    "\uffc4\031\uffc4\032\uffc4\035\uffc4\036\uffc4\037\uffc4\040\uffc4" +
    "\041\uffc4\042\uffc4\043\uffc4\044\uffc4\047\uffc4\051\uffc4\054" +
    "\uffc4\001\002\000\004\046\073\001\002\000\032\017\061" +
    "\020\057\021\052\026\070\030\071\045\051\046\054\054" +
    "\066\055\067\056\053\057\056\061\047\001\002\000\056" +
    "\004\uffc9\005\uffc9\007\uffc9\011\uffc9\012\uffc9\013\uffc9\016" +
    "\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\035\uffc9\036\uffc9" +
    "\037\uffc9\040\uffc9\041\uffc9\042\uffc9\043\uffc9\044\uffc9\047" +
    "\uffc9\051\uffc9\054\uffc9\001\002\000\032\017\061\020\057" +
    "\021\052\026\070\030\071\045\051\046\054\054\066\055" +
    "\067\056\053\057\056\061\047\001\002\000\004\047\075" +
    "\001\002\000\056\004\uffbc\005\uffbc\007\uffbc\011\uffbc\012" +
    "\uffbc\013\uffbc\016\uffbc\027\uffbc\030\uffbc\031\uffbc\032\uffbc" +
    "\035\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc\042\uffbc\043" +
    "\uffbc\044\uffbc\047\uffbc\051\uffbc\054\uffbc\001\002\000\032" +
    "\017\061\020\057\021\052\026\070\030\071\045\051\046" +
    "\054\054\066\055\067\056\053\057\056\061\047\001\002" +
    "\000\004\051\100\001\002\000\056\004\uffc5\005\uffc5\007" +
    "\uffc5\011\uffc5\012\uffc5\013\uffc5\016\uffc5\027\uffc5\030\uffc5" +
    "\031\uffc5\032\uffc5\035\uffc5\036\uffc5\037\uffc5\040\uffc5\041" +
    "\uffc5\042\uffc5\043\uffc5\044\uffc5\047\uffc5\051\uffc5\054\uffc5" +
    "\001\002\000\032\017\061\020\057\021\052\026\070\030" +
    "\071\045\051\046\054\054\066\055\067\056\053\057\056" +
    "\061\047\001\002\000\032\017\061\020\057\021\052\026" +
    "\070\030\071\045\051\046\054\054\066\055\067\056\053" +
    "\057\056\061\047\001\002\000\032\017\061\020\057\021" +
    "\052\026\070\030\071\045\051\046\054\054\066\055\067" +
    "\056\053\057\056\061\047\001\002\000\032\017\061\020" +
    "\057\021\052\026\070\030\071\045\051\046\054\054\066" +
    "\055\067\056\053\057\056\061\047\001\002\000\032\017" +
    "\061\020\057\021\052\026\070\030\071\045\051\046\054" +
    "\054\066\055\067\056\053\057\056\061\047\001\002\000" +
    "\032\017\061\020\057\021\052\026\070\030\071\045\051" +
    "\046\054\054\066\055\067\056\053\057\056\061\047\001" +
    "\002\000\032\017\061\020\057\021\052\026\070\030\071" +
    "\045\051\046\054\054\066\055\067\056\053\057\056\061" +
    "\047\001\002\000\032\017\061\020\057\021\052\026\070" +
    "\030\071\045\051\046\054\054\066\055\067\056\053\057" +
    "\056\061\047\001\002\000\036\004\uffd4\005\uffd4\007\uffd4" +
    "\011\uffd4\012\uffd4\013\uffd4\016\uffd4\027\104\030\101\043" +
    "\uffd4\044\uffd4\047\uffd4\051\uffd4\054\uffd4\001\002\000\036" +
    "\004\uffd2\005\uffd2\007\uffd2\011\uffd2\012\uffd2\013\uffd2\016" +
    "\uffd2\027\104\030\101\043\uffd2\044\uffd2\047\uffd2\051\uffd2" +
    "\054\uffd2\001\002\000\036\004\uffd3\005\uffd3\007\uffd3\011" +
    "\uffd3\012\uffd3\013\uffd3\016\uffd3\027\104\030\101\043\uffd3" +
    "\044\uffd3\047\uffd3\051\uffd3\054\uffd3\001\002\000\036\004" +
    "\uffd1\005\uffd1\007\uffd1\011\uffd1\012\uffd1\013\uffd1\016\uffd1" +
    "\027\104\030\101\043\uffd1\044\uffd1\047\uffd1\051\uffd1\054" +
    "\uffd1\001\002\000\056\004\uffcf\005\uffcf\007\uffcf\011\uffcf" +
    "\012\uffcf\013\uffcf\016\uffcf\027\uffcf\030\uffcf\031\116\032" +
    "\117\035\uffcf\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042\uffcf" +
    "\043\uffcf\044\uffcf\047\uffcf\051\uffcf\054\uffcf\001\002\000" +
    "\032\017\061\020\057\021\052\026\070\030\071\045\051" +
    "\046\054\054\066\055\067\056\053\057\056\061\047\001" +
    "\002\000\032\017\061\020\057\021\052\026\070\030\071" +
    "\045\051\046\054\054\066\055\067\056\053\057\056\061" +
    "\047\001\002\000\056\004\uffcb\005\uffcb\007\uffcb\011\uffcb" +
    "\012\uffcb\013\uffcb\016\uffcb\027\uffcb\030\uffcb\031\uffcb\032" +
    "\uffcb\035\uffcb\036\uffcb\037\uffcb\040\uffcb\041\uffcb\042\uffcb" +
    "\043\uffcb\044\uffcb\047\uffcb\051\uffcb\054\uffcb\001\002\000" +
    "\056\004\uffcc\005\uffcc\007\uffcc\011\uffcc\012\uffcc\013\uffcc" +
    "\016\uffcc\027\uffcc\030\uffcc\031\uffcc\032\uffcc\035\uffcc\036" +
    "\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\043\uffcc\044\uffcc" +
    "\047\uffcc\051\uffcc\054\uffcc\001\002\000\036\004\uffd6\005" +
    "\uffd6\007\uffd6\011\uffd6\012\uffd6\013\uffd6\016\uffd6\027\104" +
    "\030\101\043\uffd6\044\uffd6\047\uffd6\051\uffd6\054\uffd6\001" +
    "\002\000\036\004\uffd5\005\uffd5\007\uffd5\011\uffd5\012\uffd5" +
    "\013\uffd5\016\uffd5\027\104\030\101\043\uffd5\044\uffd5\047" +
    "\uffd5\051\uffd5\054\uffd5\001\002\000\056\004\uffce\005\uffce" +
    "\007\uffce\011\uffce\012\uffce\013\uffce\016\uffce\027\uffce\030" +
    "\uffce\031\116\032\117\035\uffce\036\uffce\037\uffce\040\uffce" +
    "\041\uffce\042\uffce\043\uffce\044\uffce\047\uffce\051\uffce\054" +
    "\uffce\001\002\000\032\017\061\020\057\021\052\026\070" +
    "\030\071\045\051\046\054\054\066\055\067\056\053\057" +
    "\056\061\047\001\002\000\030\004\uffd8\005\uffd8\007\uffd8" +
    "\011\uffd8\012\uffd8\013\uffd8\016\uffd8\044\uffd8\047\uffd8\051" +
    "\uffd8\054\uffd8\001\002\000\004\047\130\001\002\000\056" +
    "\004\uffbf\005\uffbf\007\uffbf\011\uffbf\012\uffbf\013\uffbf\016" +
    "\uffbf\027\uffbf\030\uffbf\031\uffbf\032\uffbf\035\uffbf\036\uffbf" +
    "\037\uffbf\040\uffbf\041\uffbf\042\uffbf\043\uffbf\044\uffbf\047" +
    "\uffbf\051\uffbf\054\uffbf\001\002\000\004\047\132\001\002" +
    "\000\056\004\uffbe\005\uffbe\007\uffbe\011\uffbe\012\uffbe\013" +
    "\uffbe\016\uffbe\027\uffbe\030\uffbe\031\uffbe\032\uffbe\035\uffbe" +
    "\036\uffbe\037\uffbe\040\uffbe\041\uffbe\042\uffbe\043\uffbe\044" +
    "\uffbe\047\uffbe\051\uffbe\054\uffbe\001\002\000\032\017\061" +
    "\020\057\021\052\026\070\030\071\045\051\046\054\054" +
    "\066\055\067\056\053\057\056\061\047\001\002\000\026" +
    "\004\uffda\005\uffda\007\uffda\011\uffda\012\uffda\013\uffda\016" +
    "\uffda\047\uffda\051\uffda\054\uffda\001\002\000\004\047\136" +
    "\001\002\000\056\004\uffc7\005\uffc7\007\uffc7\011\uffc7\012" +
    "\uffc7\013\uffc7\016\uffc7\027\uffc7\030\uffc7\031\uffc7\032\uffc7" +
    "\035\uffc7\036\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7\043" +
    "\uffc7\044\uffc7\047\uffc7\051\uffc7\054\uffc7\001\002\000\004" +
    "\047\140\001\002\000\056\004\uffbd\005\uffbd\007\uffbd\011" +
    "\uffbd\012\uffbd\013\uffbd\016\uffbd\027\uffbd\030\uffbd\031\uffbd" +
    "\032\uffbd\035\uffbd\036\uffbd\037\uffbd\040\uffbd\041\uffbd\042" +
    "\uffbd\043\uffbd\044\uffbd\047\uffbd\051\uffbd\054\uffbd\001\002" +
    "\000\056\004\uffc8\005\uffc8\007\uffc8\011\uffc8\012\uffc8\013" +
    "\uffc8\016\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8\035\uffc8" +
    "\036\uffc8\037\uffc8\040\uffc8\041\uffc8\042\uffc8\043\uffc8\044" +
    "\uffc8\047\uffc8\051\uffc8\054\uffc8\001\002\000\004\034\143" +
    "\001\002\000\032\017\061\020\057\021\052\026\070\030" +
    "\071\045\051\046\054\054\066\055\067\056\053\057\056" +
    "\061\047\001\002\000\020\005\uffe7\007\uffe7\011\uffe7\012" +
    "\uffe7\013\uffe7\016\uffe7\054\uffe7\001\002\000\020\005\uffe8" +
    "\007\uffe8\011\uffe8\012\uffe8\013\uffe8\016\uffe8\054\uffe8\001" +
    "\002\000\020\005\uffef\007\uffef\011\uffef\012\uffef\013\uffef" +
    "\016\uffef\054\uffef\001\002\000\034\017\061\020\057\021" +
    "\052\026\070\030\071\045\051\046\054\054\066\055\067" +
    "\056\053\057\056\060\151\061\047\001\002\000\004\047" +
    "\153\001\002\000\004\047\152\001\002\000\020\005\uffe5" +
    "\007\uffe5\011\uffe5\012\uffe5\013\uffe5\016\uffe5\054\uffe5\001" +
    "\002\000\020\005\uffe6\007\uffe6\011\uffe6\012\uffe6\013\uffe6" +
    "\016\uffe6\054\uffe6\001\002\000\004\004\155\001\002\000" +
    "\020\005\ufff0\007\027\011\044\012\040\013\035\016\036" +
    "\054\043\001\002\000\004\005\157\001\002\000\024\005" +
    "\uffe0\007\uffe0\011\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0" +
    "\016\uffe0\054\uffe0\001\002\000\024\005\uffde\007\uffde\011" +
    "\uffde\012\uffde\013\uffde\014\162\015\161\016\uffde\054\uffde" +
    "\001\002\000\004\004\170\001\002\000\032\017\061\020" +
    "\057\021\052\026\070\030\071\045\051\046\054\054\066" +
    "\055\067\056\053\057\056\061\047\001\002\000\020\005" +
    "\uffe2\007\uffe2\011\uffe2\012\uffe2\013\uffe2\016\uffe2\054\uffe2" +
    "\001\002\000\004\004\165\001\002\000\020\005\ufff0\007" +
    "\027\011\044\012\040\013\035\016\036\054\043\001\002" +
    "\000\004\005\167\001\002\000\024\005\uffe1\007\uffe1\011" +
    "\uffe1\012\uffe1\013\uffe1\014\uffe1\015\uffe1\016\uffe1\054\uffe1" +
    "\001\002\000\020\005\ufff0\007\027\011\044\012\040\013" +
    "\035\016\036\054\043\001\002\000\004\005\172\001\002" +
    "\000\020\005\uffdf\007\uffdf\011\uffdf\012\uffdf\013\uffdf\016" +
    "\uffdf\054\uffdf\001\002\000\004\002\ufff3\001\002\000\004" +
    "\004\175\001\002\000\020\005\ufff0\007\027\011\044\012" +
    "\040\013\035\016\036\054\043\001\002\000\004\005\177" +
    "\001\002\000\022\005\uffdb\007\uffdb\010\uffdb\011\uffdb\012" +
    "\uffdb\013\uffdb\016\uffdb\054\uffdb\001\002\000\022\005\uffdd" +
    "\007\uffdd\010\201\011\uffdd\012\uffdd\013\uffdd\016\uffdd\054" +
    "\uffdd\001\002\000\032\017\061\020\057\021\052\026\070" +
    "\030\071\045\051\046\054\054\066\055\067\056\053\057" +
    "\056\061\047\001\002\000\004\004\203\001\002\000\020" +
    "\005\ufff0\007\027\011\044\012\040\013\035\016\036\054" +
    "\043\001\002\000\004\005\205\001\002\000\022\005\uffdc" +
    "\007\uffdc\010\uffdc\011\uffdc\012\uffdc\013\uffdc\016\uffdc\054" +
    "\uffdc\001\002\000\004\002\001\001\002\000\004\055\210" +
    "\001\002\000\004\051\211\001\002\000\004\053\ufff6\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\016\002\007\003\003\004\010\005\012\006" +
    "\011\007\013\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\023\001\001\000\002\001\001\000\006\006\022" +
    "\007\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\016\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\012\041\013\030" +
    "\014\031\015\033\016\036\017\040\022\027\024\032\001" +
    "\001\000\020\025\173\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\025\153\026\054\027\061\030\064\031\063\032" +
    "\062\033\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\014\145\015" +
    "\033\016\036\017\040\022\027\024\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\025\144\026\054\027" +
    "\061\030\064\031\063\032\062\033\057\001\001\000\020" +
    "\025\047\026\054\027\061\030\064\031\063\032\062\033" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\032\140\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\025\134\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\032\071\033\057\001\001\000\002\001" +
    "\001\000\020\025\073\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\025\076\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\031\123\032\062\033\057\001\001\000\012" +
    "\030\122\031\063\032\062\033\057\001\001\000\012\030" +
    "\121\031\063\032\062\033\057\001\001\000\010\031\114" +
    "\032\062\033\057\001\001\000\012\030\113\031\063\032" +
    "\062\033\057\001\001\000\012\030\112\031\063\032\062" +
    "\033\057\001\001\000\012\030\111\031\063\032\062\033" +
    "\057\001\001\000\012\030\110\031\063\032\062\033\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\032\120" +
    "\033\057\001\001\000\006\032\117\033\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\026\125\027\061\030" +
    "\064\031\063\032\062\033\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\025\133\026\054\027\061\030\064" +
    "\031\063\032\062\033\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\025" +
    "\143\026\054\027\061\030\064\031\063\032\062\033\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\025\147\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\012\041\013\155\014\031\015\033\016\036\017" +
    "\040\022\027\024\032\001\001\000\002\001\001\000\004" +
    "\020\157\001\001\000\004\021\162\001\001\000\002\001" +
    "\001\000\020\025\163\026\054\027\061\030\064\031\063" +
    "\032\062\033\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\012\041\013\165\014\031\015\033\016\036" +
    "\017\040\022\027\024\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\012\041\013\170\014\031\015\033" +
    "\016\036\017\040\022\027\024\032\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\012\041\013\175\014\031\015\033\016\036\017" +
    "\040\022\027\024\032\001\001\000\002\001\001\000\004" +
    "\023\177\001\001\000\002\001\001\000\020\025\201\026" +
    "\054\027\061\030\064\031\063\032\062\033\057\001\001" +
    "\000\002\001\001\000\022\012\041\013\203\014\031\015" +
    "\033\016\036\017\040\022\027\024\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public TablaSimbolos tablaSimbolos = new TablaSimbolos();

    // Método para manejar errores sintácticos recuperables
    public void syntax_error(Symbol symbol) {
        System.err.println("Error Sintáctico: Línea " + (symbol.left) +  ", columna " + (symbol.right) + ". No se esperaba el componente: " + symbol.value + ".");
    }

    // Método para manejar errores sintácticos fatales
    public void unrecovered_syntax_error(Symbol symbol) throws java.lang.Exception {
        System.err.println("Error Fatal: No se pudo recuperar del error en la línea " + (symbol.left) + ", columna " + (symbol.right) + ".");
        throw new Exception("Error Sintáctico Fatal.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= programa 
            {
              String RESULT =null;
		
            System.out.println("\n[PARSER] Compilación exitosa");
            tablaSimbolos.generarArchivo("compilador/src/tablaSimbolos.txt");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= zona_declaraciones bloque_programa 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: programa -> zona_declaraciones bloque_programa");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // zona_declaraciones ::= lista_declaraciones 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: zona_declaraciones -> lista_declaraciones");
            System.out.println("---------------------------------------------------");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("zona_declaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // zona_declaraciones ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("zona_declaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_declaraciones ::= lista_declaraciones declaracion 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_declaraciones ::= declaracion 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= tipo DOS_PUNTOS lista_variables 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: declaracion -> tipo DOS_PUNTOS lista_variables");
            System.out.println("[PARSER] VALOR: " + t + ": " + v);

            String[] vars = v.split(",");
            for (String var : vars) {
                parser.tablaSimbolos.agregarVariable(var.trim(), t);
            }

            System.out.println("---------------------------------------------------");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo ::= INT 
            {
              String RESULT =null;
		 RESULT = "INT"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo ::= FLOAT 
            {
              String RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo ::= BOOLEAN 
            {
              String RESULT =null;
		 RESULT = "BOOLEAN"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo ::= ARRAY CORCHETE_IZQ ENTERO CORCHETE_DER 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "ARRAY[" + e + "]"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_variables ::= lista_variables COMA IDENTIFICADOR 
            {
              String RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String lista = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lista + ", " + id; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_variables ::= IDENTIFICADOR 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = id; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // bloque_programa ::= PROGRAM INDENT sentencias_opcionales DEDENT 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: bloque_programa -> PROGRAM INDENT sentencias DEDENT");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_programa",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // bloque_programa ::= PROGRAM 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_programa",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencias_opcionales ::= sentencias 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias_opcionales",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencias_opcionales ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias_opcionales",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencias ::= sentencias sentencia 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencias ::= sentencia 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= sentencia_asignacion 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= sentencia_if 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= sentencia_while 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= sentencia_print 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= sentencia_control 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia_asignacion ::= IDENTIFICADOR ASIGNACION expr 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: sentencia_asignacion -> IDENTIFICADOR ASIGNACION expr");
            System.out.println("[PARSER] VALOR: " + id + " = " + e);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia_asignacion ::= IDENTIFICADOR CORCHETE_IZQ expr CORCHETE_DER ASIGNACION expr 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idxleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idxright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String idx = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: sentencia_asignacion -> IDENTIFICADOR [ expr ] ASIGNACION expr");
            System.out.println("[PARSER] VALOR: " + id + "[" + idx + "] = " + e);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia_print ::= PRINT PARENTESIS_IZQ expr PARENTESIS_DER 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.out.println("[PARSER] REGLA: sentencia_print -> PRINT ( expr )");
            System.out.println("[PARSER] VALOR: Imprimir -> (" + e + ")");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_print",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_print ::= PRINT PARENTESIS_IZQ CADENA PARENTESIS_DER 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.out.println("[PARSER] REGLA: sentencia_print -> PRINT ( CADENA )");
            System.out.println("[PARSER] VALOR: Imprimir -> (" + c + ")");

            parser.tablaSimbolos.agregarString(c);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_print",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_control ::= BREAK 
            {
              String RESULT =null;
		 System.out.println("[PARSER] REGLA: sentencia_control -> BREAK"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_control",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia_control ::= CONTINUE 
            {
              String RESULT =null;
		 System.out.println("[PARSER] REGLA: sentencia_control -> CONTINUE"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_control",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia_if ::= IF expr INDENT sentencias_opcionales DEDENT lista_elif bloque_else 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: sentencia_if -> IF expr INDENT sentencias DEDENT lista_elif bloque_else");
            System.out.println("---------------------------------------------------");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_elif ::= lista_elif ELIF expr INDENT sentencias_opcionales DEDENT 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_elif",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_elif ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_elif",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // bloque_else ::= ELSE INDENT sentencias_opcionales DEDENT 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_else",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bloque_else ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_else",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sentencia_while ::= WHILE expr INDENT sentencias_opcionales DEDENT lista_alt_while 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: sentencia_while -> WHILE expr INDENT sentencias DEDENT lista_alt_while");
            System.out.println("---------------------------------------------------");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_while",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // lista_alt_while ::= lista_alt_while ALT_WHILE expr INDENT sentencias_opcionales DEDENT 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_alt_while",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_alt_while ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_alt_while",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr_and DISYUNCION expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr -> expr_and DISYUNCION expr");
            RESULT = e1 + "||" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr_and 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr_and ::= expr_rel CONJUNCION expr_and 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_and -> expr_rel CONJUNCION expr_and");
            RESULT = e1 + "&&" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_and",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr_and ::= expr_rel 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_and",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr_rel ::= expr_arit IGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit IGUAL expr_arit");
            RESULT = e1 + "==" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr_rel ::= expr_arit DESIGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit DESIGUAL expr_arit");
            RESULT = e1 + "!=" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr_rel ::= expr_arit MAYOR_IGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MAYOR_IGUAL expr_arit");
            RESULT = e1 + ">=" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr_rel ::= expr_arit MENOR_IGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MENOR_IGUAL expr_arit");
            RESULT = e1 + "<=" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr_rel ::= expr_arit MAYOR expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MAYOR expr_arit");
            RESULT = e1 + ">" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr_rel ::= expr_arit MENOR expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_rel -> expr_arit MENOR expr_arit");
            RESULT = e1 + "<" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr_rel ::= expr_arit 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_rel",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr_arit ::= expr_arit SUMA term 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_arit -> expr_arit SUMA term");
            RESULT = e1 + "+" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr_arit ::= expr_arit RESTA term 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: expr_arit -> expr_arit RESTA term");
            RESULT = e1 + "-" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr_arit ::= term 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // term ::= term MULTIPLICACION factor 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
            System.out.println("[PARSER] REGLA: term -> term MULTIPLICACION factor");
            RESULT = e1 + "*" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // term ::= term DIVISION factor 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
            System.out.println("[PARSER] REGLA: term -> term DIVISION factor");
            RESULT = e1 + "/" + e2;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // term ::= factor 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= RESTA factor 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> MENOS_UNARIO factor");
            RESULT = "-" + e;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= NEGACION factor 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> NEGACION factor");
            RESULT = "!" + e;
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= PARENTESIS_IZQ expr PARENTESIS_DER 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.out.println("[PARSER] REGLA: factor -> ( expr )");
            RESULT = "(" + e + ")";
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= IDENTIFICADOR 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> IDENTIFICADOR");
            RESULT = id;
            System.out.println("[PARSER] VALOR: " + id);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= IDENTIFICADOR CORCHETE_IZQ expr CORCHETE_DER 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.out.println("[PARSER] REGLA: factor -> IDENTIFICADOR [ expr ]");
            RESULT = id + "[" + e + "]";
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= ENTERO 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> ENTERO");
            RESULT = e;
            System.out.println("[PARSER] VALOR: " + e);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= FLOTANTE 
            {
              String RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> FLOTANTE");
            RESULT = f;
            System.out.println("[PARSER] VALOR: " + f);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= BOOLEANO 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> BOOLEANO");
            RESULT = b;
            System.out.println("[PARSER] VALOR: " + b);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= ARREGLO 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            System.out.println("[PARSER] REGLA: factor -> ARREGLO");
            RESULT = a;
            System.out.println("[PARSER] VALOR: " + a);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // factor ::= expr_moda 
            {
              String RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String m = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = m; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // factor ::= READ_INT PARENTESIS_IZQ PARENTESIS_DER 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: factor -> READ_INT ()");
            RESULT = "READ_INT()";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // factor ::= READ_FLOAT PARENTESIS_IZQ PARENTESIS_DER 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: factor -> READ_FLOAT ()");
            RESULT = "READ_FLOAT()";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // factor ::= READ_BOOL PARENTESIS_IZQ PARENTESIS_DER 
            {
              String RESULT =null;
		
            System.out.println("[PARSER] REGLA: factor -> READ_BOOL ()");
            RESULT = "READ_BOOL()";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr_moda ::= MODA PARENTESIS_IZQ expr PARENTESIS_DER 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.out.println("[PARSER] REGLA: expr_moda -> MODA ( expr )");
            RESULT = "moda(" + e + ")";
            System.out.println("[PARSER] VALOR: " + RESULT);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_moda",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
