
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package unnoba;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_IZQ = 35;
  public static final int ENTERO = 42;
  public static final int RESTA = 22;
  public static final int DOS_PUNTOS = 40;
  public static final int CONTINUE = 8;
  public static final int CORCHETE_DER = 38;
  public static final int INT = 16;
  public static final int ARRAY = 19;
  public static final int IDENTIFICADOR = 41;
  public static final int IGUAL = 26;
  public static final int SUMA = 21;
  public static final int IF = 9;
  public static final int ARREGLO = 46;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int PARENTESIS_DER = 36;
  public static final int READ_FLOAT = 14;
  public static final int error = 1;
  public static final int PROGRAM = 4;
  public static final int COMA = 39;
  public static final int CADENA = 45;
  public static final int NEGACION = 34;
  public static final int MENOR = 31;
  public static final int MODA = 20;
  public static final int BREAK = 7;
  public static final int ALT_WHILE = 6;
  public static final int DESIGUAL = 27;
  public static final int ASIGNACION = 25;
  public static final int MAYOR = 30;
  public static final int READ_INT = 13;
  public static final int ELSE = 11;
  public static final int WHILE = 5;
  public static final int CORCHETE_IZQ = 37;
  public static final int DEDENT = 3;
  public static final int MAYOR_IGUAL = 28;
  public static final int FLOAT = 17;
  public static final int CONJUNCION = 32;
  public static final int BOOLEANO = 44;
  public static final int DISYUNCION = 33;
  public static final int MENOR_IGUAL = 29;
  public static final int INDENT = 2;
  public static final int DIVISION = 24;
  public static final int READ_BOOL = 15;
  public static final int FLOTANTE = 43;
  public static final int ELIF = 10;
  public static final int PRINT = 12;
  public static final int MULTIPLICACION = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INDENT",
  "DEDENT",
  "PROGRAM",
  "WHILE",
  "ALT_WHILE",
  "BREAK",
  "CONTINUE",
  "IF",
  "ELIF",
  "ELSE",
  "PRINT",
  "READ_INT",
  "READ_FLOAT",
  "READ_BOOL",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "ARRAY",
  "MODA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ASIGNACION",
  "IGUAL",
  "DESIGUAL",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "COMA",
  "DOS_PUNTOS",
  "IDENTIFICADOR",
  "ENTERO",
  "FLOTANTE",
  "BOOLEANO",
  "CADENA",
  "ARREGLO"
  };
}

